### ISSUE TITLE
main.py wont run

### ISSUE THREAD

**Issue by mryani-UG** [i-UG/tickets#31]
Successful program on pico.  Won't run when left just to pico (ie. no Thonny...).

# Rui Santos & Sara Santos - Random Nerd Tutorials
# Complete project details at https://RandomNerdTutorials.com/raspberry-pi-pico-w-mqtt-micropython/
import time
from machine import Pin
from time import sleep
import network
from umqtt.simple import MQTTClient

# Define LED
led = Pin('LED', Pin.OUT)
light = Pin(28, Pin.OUT)

# Constants for MQTT Topics
MQTT_TOPIC_LED = 'PICO4'

# MQTT Parameters
MQTT_SERVER = '172.16.1.104'
MQTT_PORT = 1883
MQTT_USER = 'pimike'
MQTT_PASSWORD = 'pimike'
MQTT_CLIENT_ID = ''
MQTT_KEEPALIVE = 7200
##MQTT_SSL = True
##MQTT_SSL_PARAMS = {'server_hostname': MQTT_SERVER}

print('After Definitions')

# Init Wi-Fi Interface
##def initialize_wifi(ssid, password):
wlan = network.WLAN(network.STA_IF)
wlan.active(True)
wlan.connect("Essist","28J62399H8Y2A")
    # Connect to the network

print('After wlan connection')

time.sleep(5)
    
print('After all WLAN')
 
 # Connect to MQTT Broker
def connect_mqtt():
    try:
        client = MQTTClient(client_id=MQTT_CLIENT_ID,
                            server=MQTT_SERVER,
                            port=MQTT_PORT,
                            user=MQTT_USER,
                            password=MQTT_PASSWORD,
                            keepalive=MQTT_KEEPALIVE)

        client.connect()
        print('CONNECTED TO MQTT')
        return client
    except Exception as e:
        print('Error connecting to MQTT:', e)

# Subcribe to MQTT topics
def subscribe(client, topic):
    client.subscribe(topic)
    print('Subscribe to topic:', topic, client)

 # Callback function that runs when you receive a message on subscribed topic
def my_callback(topic, message):
    # Perform desired actions based on the subscribed topic and response
    print('Received message on topic:', topic)
    print('Response:', message)
    # Check the content of the received message
    if message == b'ON':
        print('Turning LED ON')
        led.value(1)  # Turn LED ON
        light.value(1)  # Turn LED ON
    elif message == b'OFF':
        print('Turning LED OFF')
        led.value(0)  # Turn LED OFF      
        light.value(0)  # Turn LED OFF
    else:
        print('Unknown command')
   
try:

        print('Inside Try')

        client = connect_mqtt()
        client.set_callback(my_callback)
        subscribe(client, MQTT_TOPIC_LED)
        
        # Continuously checking for messages
        while True:
            sleep(5)
            client.check_msg()
            print( 'client_stuff', MQTT_CLIENT_ID, MQTT_SERVER, MQTT_PORT, MQTT_USER, MQTT_PASSWORD, MQTT_TOPIC_LED)
            print('Loop running')
except Exception as e:
    print('Error:', e)

**Comment by AndyYouens** [comment]
What is the output log when running from Thorney? @mryani-UG

**Comment by mryani-UG** [comment]
It runs just fine from Thonny.  Either using r to e code on my PC or running the main.py code on the Pico.

Just doesn’t seem to be running when I shut down Thonny and reboot the Pico.
________________________________

**Comment by AndyYouens** [comment]
please re flash the pico with the latest nightly updates.

**Comment by mryani-UG** [comment]
Hi Andy.  I'm not sure that I know what you mean there.  
But...  I tried putting in code to activate the led at various points just to see where the code got up to.  The issue was that it was not connecting to the MQTT server.  Ironically, it then started to work and I think it is because of the 'sleep' statements I put in for the led.  So, the pico was not being given enough time to connect.  Does that make sense?

**Comment by AndyYouens** [comment]
Hi mke
Yes, it does.  I still think you need to completely wipe the pico & put on the latest firmware, then try your code again.

It is always a good practice to put on the latest firmware.

https://micropython.org/download/RPI_PICO/

**Comment by AndyYouens** [comment]
Hi @mryani-UG 

can this be closed now as the original issue has been resolved?

**Comment by mryani-UG** [comment]
Yes.  This is closed.  May thanks fir the upgrade tip.

Cheers

Mike R
